import Footer from "@/components/footer"
import NavBar from "@/components/navbar"

import type { Metadata } from "next"
import "./globals.css";
import React from "react"
import { Inter } from 'next/font/google';
import { AuthProvider } from "@/context/AuthContext";


const inter = Inter({subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en"> 
        <body>
          <NavBar/> 
          {children}
          <Footer/>
        </body>
      </html>
    </AuthProvider>
  )
}

